export const ROUTES = {
  ONBOARDING: 'OnBoarding',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  INAPPPURCHASE: 'InAppPurchase',
  FORGOT_PASSWORD: 'ForgotPassword',
  MAIN: 'Main',
  HOME: 'Home',
  AI_ASSISTANCE: 'AI Assistance',
  VOICE_CHAT: 'Chat',
  HISTORY: 'History',
  PROFILE: 'Profile',
  SETTING: 'Setting',
  AIVO_CHAT: 'AivoChat',
};
