export const LABELS = {
  UPGRADE: 'Upgrade Premium',
  GENERATED_AI_IMAGE: 'Generated Unlimited AI Images',
  HIGHER_WORDS_LIMIT: 'Higher Words Limit',
  NO_ADS: 'No Ads',
  NO_LIMITS: 'No Limits',
  SELECT_PLANS: 'SELECT PLANS',
  WEEKLY: 'Weekly Subscriptions',
  MONTHLY: 'Monthly Subscriptions',
  YEARLY: 'Yearly Subscriptions',
  POPULAR: 'Popular',
  DOLLAR: '$',
  WEEK: '/week',
  MONTH: '/month',
  YEAR: '/year',
  WELCOME: 'Welcome!',
  GREETWELCOME:
    'Welcome to AI AIVO!, Your trusted company for intelligent interactions.',
  PLACEHOLDEREMAIL: 'Email Address',
  PLACEHOLDERPASSWORD: 'Password',
  FORGOTPASSWORD: 'Forgot Password?',
  SUBMIT: 'Submit',
  DONTHAVEACCOUNT: "Don't have an account?",
  SIGNUP: 'Sign Up',
  REGISTER: 'Register Here',
  PLACEHOLDERFULLNAME: 'Enter the full name',
  EMAIL: 'Enter the email address',
  PLACEHOLDERCONFIRMPASSWORD: 'Confirm Password',
  HAVEALREADYACCOUNT: 'Have already an account?',
  SIGNIN: 'Sign In',
  CAMERA: 'Camera',
  GALLERY: 'GALLERY',
};
