export const LABELS = {
  UPGRADE: 'Upgrade Premium',
  GENERATED_AI_IMAGE: 'Generated Unlimited AI Images',
  HIGHER_WORDS_LIMIT: 'Higher Words Limit',
  NO_ADS: 'No Ads',
  NO_LIMITS: 'No Limits',
  SELECT_PLANS: 'SELECT PLANS',
  WEEKLY: 'Weekly Subscriptions',
  MONTHLY: 'Monthly Subscriptions',
  YEARLY: 'Yearly Subscriptions',
  POPULAR: 'Popular',
  DOLLAR: '$',
  WEEK: '/week',
  MONTH: '/month',
  YEAR: '/year',
  PRIVACY: 'Privacy',
  TERMS: 'Terms',
  CANCEL_ANYTIME: 'Cancel Anytime',
  SAVE30: 'SAVE 30%',
  SAVE70: 'SAVE 70%',
  SUBSCRIPTION_BUTTON: 'Start free trial and Plan',
  WELCOME: 'Welcome!',
  GREET_WELCOME:
    'Welcome to AI AIVO!, Our trusted company for intelligent interactions.',
  PLACEHOLDER_EMAIL: 'Email Address',
  PLACEHOLDER_PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  SUBMIT: 'Submit',
  DON_T_HAVE_ACCOUNT: "Don't have an account?",
  SIGN_UP: 'Sign Up',
  REGISTER: 'Register Here',
  PLACEHOLDER_FULL_NAME: 'Enter the full name',
  EMAIL: 'Enter the email address',
  PLACEHOLDER_CONFIRM_PASSWORD: 'Confirm Password',
  HAVE_ALREADY_ACCOUNT: 'Have already an account?',
  SIGN_IN: 'Sign In',
  CAMERA: 'Camera',
  GALLERY: 'GALLERY',
  FORGOT_PASSWORD_LABEL: 'Forgot Password',
  FORGOT_DESCRIPTION: `We'll send reset password link to your email address. You can change
  password to the link.`,
};
