export const LABELS = {
  UPGRADE: 'Upgrade Premium',
  GENERATEDAIIMAGE: 'Generated Unlimited AI Images',
  HIGHERWORDSLIMIT: 'Higher Words Limit',
  NOADS: 'No Ads',
  NOLIMITS: 'No Limits',
  SELECTPLANS: 'SELECT PLANS',
  WEEKLY: 'Weekly Subscriptions',
  MONTHLY: 'Monthly Subscriptions',
  YEARLY: 'Yearly Subscriptions',
  POPULAR: 'Popular',
  DOLLAR: '$',
  WEEK: '/week',
  MONTH: '/month',
  YEAR: '/year',
  WELCOME: 'Welcome!',
  GREETWELCOME:
    'Welcome to AI AIVO!, Your trusted company for intelligent interactions.',
  PLACEHOLDEREMAIL: 'Email Address',
  PLACEHOLDERPASSWORD: 'Password',
  FORGOTPASSWORD: 'Forgot Password?',
  SUBMIT: 'Submit',
  DONTHAVEACCOUNT: "Don't have an account?",
  SIGNUP: 'Sign Up',
  REGISTER: 'Register Here',
};
